INSERT INTO [StaticModel].[LocalisationKeys] ([Key], [DefaultValue]) VALUES
('welcome', 'Welcome {{ fullname }}')
GO

INSERT [StaticModel].[Languages] ([IsoAlpha2], [Name]) VALUES 
('AB', 'Abkhazian')
,('AA', 'Afar')
,('AF', 'Afrikaans')
,('AK', 'Akan')
,('SQ', 'Albanian')
,('AM', 'Amharic')
,('AR', 'Arabic')
,('AN', 'Aragonese')
,('HY', 'Armenian')
,('AS', 'Assamese')
,('AV', 'Avaric')
,('AE', 'Avestan')
,('AY', 'Aymara')
,('AZ', 'Azerbaijani')
,('BM', 'Bambara')
,('BA', 'Bashkir')
,('EU', 'Basque')
,('BE', 'Belarusian')
,('BN', 'Bengali')
,('BH', 'Bihari languages')
,('BI', 'Bislama')
,('NB', 'Bokmål, Norwegian')
,('BS', 'Bosnian')
,('BR', 'Breton')
,('BG', 'Bulgarian')
,('MY', 'Burmese')
,('ES', 'Castilian')
,('CA', 'Catalan')
,('KM', 'Central Khmer')
,('CH', 'Chamorro')
,('CE', 'Chechen')
,('NY', 'Chewa')
,('ZH', 'Chinese')
,('ZA', 'Chuang')
,('CU', 'Church Slavic')
,('CV', 'Chuvash')
,('KW', 'Cornish')
,('CO', 'Corsican')
,('CR', 'Cree')
,('HR', 'Croatian')
,('CS', 'Czech')
,('DA', 'Danish')
,('DV', 'Dhivehi')
,('NL', 'Dutch')
,('DZ', 'Dzongkha')
,('EN', 'English')
,('EO', 'Esperanto')
,('ET', 'Estonian')
,('EE', 'Ewe')
,('FO', 'Faroese')
,('FJ', 'Fijian')
,('FI', 'Suomi')
,('FR', 'Français')
,('FF', 'Fulah')
,('GD', 'Gaelic')
,('GL', 'Galician')
,('LG', 'Ganda')
,('KA', 'Georgian')
,('DE', 'Deutsch')
,('KI', 'Gikuyu')
,('EL', 'Greek, Modern (1453-)')
,('KL', 'Greenlandic')
,('GN', 'Guarani')
,('GU', 'Gujarati')
,('HT', 'Haitian')
,('HA', 'Hausa')
,('HE', 'Hebrew')
,('HZ', 'Herero')
,('HI', 'Hindi')
,('HO', 'Hiri Motu')
,('HU', 'Hungarian')
,('IS', 'Icelandic')
,('IO', 'Ido')
,('IG', 'Igbo')
,('ID', 'Indonesian')
,('IA', 'Interlingua (International Auxiliary Language Association)')
,('IE', 'Interlingue')
,('IU', 'Inuktitut')
,('IK', 'Inupiaq')
,('GA', 'Irish')
,('IT', 'Italiano')
,('JA', 'Japanese')
,('JV', 'Javanese')
,('KN', 'Kannada')
,('KR', 'Kanuri')
,('KS', 'Kashmiri')
,('KK', 'Kazakh')
,('RW', 'Kinyarwanda')
,('KY', 'Kirghiz')
,('KV', 'Komi')
,('KG', 'Kongo')
,('KO', 'Korean')
,('KJ', 'Kuanyama')
,('KU', 'Kurdish')
,('LO', 'Lao')
,('LA', 'Latin')
,('LV', 'Latvian')
,('LB', 'Letzeburgesch')
,('LI', 'Limburgan')
,('LN', 'Lingala')
,('LT', 'Lithuanian')
,('LU', 'Luba-Katanga')
,('MK', 'Macedonian')
,('MG', 'Malagasy')
,('MS', 'Malay')
,('ML', 'Malayalam')
,('MT', 'Maltese')
,('GV', 'Manx')
,('MI', 'Maori')
,('MR', 'Marathi')
,('MH', 'Marshallese')
,('RO', 'Moldavian')
,('MN', 'Mongolian')
,('NA', 'Nauru')
,('NV', 'Navaho')
,('ND', 'Ndebele, North')
,('NR', 'Ndebele, South')
,('NG', 'Ndonga')
,('NE', 'Nepali')
,('SE', 'Northern Sami')
,('NO', 'Norwegian')
,('NN', 'Norwegian Nynorsk')
,('II', 'Nuosu')
,('OC', 'Occitan (post 1500)')
,('OJ', 'Ojibwa')
,('OR', 'Oriya')
,('OM', 'Oromo')
,('OS', 'Ossetian')
,('PI', 'Pali')
,('PA', 'Panjabi')
,('PS', 'Pashto')
,('FA', 'Persian')
,('PL', 'Polish')
,('PT', 'Portuguese')
,('QU', 'Quechua')
,('RM', 'Romansh')
,('RN', 'Rundi')
,('RU', 'Russian')
,('SM', 'Samoan')
,('SG', 'Sango')
,('SA', 'Sanskrit')
,('SC', 'Sardinian')
,('SR', 'Serbian')
,('SN', 'Shona')
,('SD', 'Sindhi')
,('SI', 'Sinhala')
,('SK', 'Slovak')
,('SL', 'Slovenian')
,('SO', 'Somali')
,('ST', 'Sotho, Southern')
,('SU', 'Sundanese')
,('SW', 'Swahili')
,('SS', 'Swati')
,('SV', 'Swedish')
,('TL', 'Tagalog')
,('TY', 'Tahitian')
,('TG', 'Tajik')
,('TA', 'Tamil')
,('TT', 'Tatar')
,('TE', 'Telugu')
,('TH', 'Thai')
,('BO', 'Tibetan')
,('TI', 'Tigrinya')
,('TO', 'Tonga (Tonga Islands)')
,('TS', 'Tsonga')
,('TN', 'Tswana')
,('TR', 'Turkish')
,('TK', 'Turkmen')
,('TW', 'Twi')
,('UG', 'Uighur')
,('UK', 'Ukrainian')
,('UR', 'Urdu')
,('UZ', 'Uzbek')
,('VE', 'Venda')
,('VI', 'Vietnamese')
,('VO', 'Volapük')
,('WA', 'Walloon')
,('CY', 'Welsh')
,('FY', 'Western Frisian')
,('WO', 'Wolof')
,('XH', 'Xhosa')
,('YI', 'Yiddish')
,('YO', 'Yoruba')
,('ZU', 'Zulu')
GO

INSERT [StaticModel].[Countries] ([IsoAlpha2], [IsoAlpha3], [Name], [NumericCode]) VALUES 
(N'AD', N'AND', N'Andorra', N'20 ')
,(N'AE', N'ARE', N'United Arab Emirates', N'784')
,(N'AF', N'AFG', N'Afghanistan', N'4  ')
,(N'AG', N'ATG', N'Antigua and Barbuda', N'28 ')
,(N'AI', N'AIA', N'Anguilla', N'660')
,(N'AL', N'ALB', N'Albania', N'8  ')
,(N'AM', N'ARM', N'Armenia', N'51 ')
,(N'AO', N'AGO', N'Angola', N'24 ')
,(N'AQ', N'ATA', N'Antarctica', N'10 ')
,(N'AR', N'ARG', N'Argentina', N'32 ')
,(N'AS', N'ASM', N'American Samoa', N'16 ')
,(N'AT', N'AUT', N'Austria', N'40 ')
,(N'AU', N'AUS', N'Australia', N'36 ')
,(N'AW', N'ABW', N'Aruba', N'533')
,(N'AX', N'ALA', N'Åland Islands', N'248')
,(N'AZ', N'AZE', N'Azerbaijan', N'31 ')
,(N'BA', N'BIH', N'Bosnia and Herzegovina', N'70 ')
,(N'BB', N'BRB', N'Barbados', N'52 ')
,(N'BD', N'BGD', N'Bangladesh', N'50 ')
,(N'BE', N'BEL', N'Belgium', N'56 ')
,(N'BF', N'BFA', N'Burkina Faso', N'854')
,(N'BG', N'BGR', N'Bulgaria', N'100')
,(N'BH', N'BHR', N'Bahrain', N'48 ')
,(N'BI', N'BDI', N'Burundi', N'108')
,(N'BJ', N'BEN', N'Benin', N'204')
,(N'BL', N'BLM', N'Saint Barthélemy', N'652')
,(N'BM', N'BMU', N'Bermuda', N'60 ')
,(N'BN', N'BRN', N'Brunei Darussalam', N'96 ')
,(N'BO', N'BOL', N'Bolivia, Plurinational State of', N'68 ')
,(N'BQ', N'BES', N'Bonaire, Sint Eustatius and Saba', N'535')
,(N'BR', N'BRA', N'Brazil', N'76 ')
,(N'BS', N'BHS', N'Bahamas', N'44 ')
,(N'BT', N'BTN', N'Bhutan', N'64 ')
,(N'BV', N'BVT', N'Bouvet Island', N'74 ')
,(N'BW', N'BWA', N'Botswana', N'72 ')
,(N'BY', N'BLR', N'Belarus', N'112')
,(N'BZ', N'BLZ', N'Belize', N'84 ')
,(N'CA', N'CAN', N'Canada', N'124')
,(N'CC', N'CCK', N'Cocos (Keeling) Islands', N'166')
,(N'CD', N'COD', N'Congo, the Democratic Republic of the', N'180')
,(N'CF', N'CAF', N'Central African Republic', N'140')
,(N'CG', N'COG', N'Congo', N'178')
,(N'CH', N'CHE', N'Switzerland', N'756')
,(N'CI', N'CIV', N'Côte d''Ivoire', N'384')
,(N'CK', N'COK', N'Cook Islands', N'184')
,(N'CL', N'CHL', N'Chile', N'152')
,(N'CM', N'CMR', N'Cameroon', N'120')
,(N'CN', N'CHN', N'China', N'156')
,(N'CO', N'COL', N'Colombia', N'170')
,(N'CR', N'CRI', N'Costa Rica', N'188')
,(N'CU', N'CUB', N'Cuba', N'192')
,(N'CV', N'CPV', N'Cape Verde', N'132')
,(N'CW', N'CUW', N'Cura', N'531')
,(N'CX', N'CXR', N'Christmas Island', N'162')
,(N'CY', N'CYP', N'Cyprus', N'196')
,(N'CZ', N'CZE', N'Czech Republic', N'203')
,(N'DE', N'DEU', N'Germany', N'276')
,(N'DJ', N'DJI', N'Djibouti', N'262')
,(N'DK', N'DNK', N'Denmark', N'208')
,(N'DM', N'DMA', N'Dominica', N'212')
,(N'DO', N'DOM', N'Dominican Republic', N'214')
,(N'DZ', N'DZA', N'Algeria', N'12 ')
,(N'EC', N'ECU', N'Ecuador', N'218')
,(N'EE', N'EST', N'Estonia', N'233')
,(N'EG', N'EGY', N'Egypt', N'818')
,(N'EH', N'ESH', N'Western Sahara', N'732')
,(N'ER', N'ERI', N'Eritrea', N'232')
,(N'ES', N'ESP', N'Spain', N'724')
,(N'ET', N'ETH', N'Ethiopia', N'231')
,(N'FI', N'FIN', N'Finland', N'246')
,(N'FJ', N'FJI', N'Fiji', N'242')
,(N'FK', N'FLK', N'Falkland Islands (Malvinas)', N'238')
,(N'FM', N'FSM', N'Micronesia, Federated States of', N'583')
,(N'FO', N'FRO', N'Faroe Islands', N'234')
,(N'FR', N'FRA', N'France', N'250')
,(N'GA', N'GAB', N'Gabon', N'266')
,(N'GB', N'GBR', N'United Kingdom', N'826')
,(N'GD', N'GRD', N'Grenada', N'308')
,(N'GE', N'GEO', N'Georgia', N'268')
,(N'GF', N'GUF', N'French Guiana', N'254')
,(N'GG', N'GGY', N'Guernsey', N'831')
,(N'GH', N'GHA', N'Ghana', N'288')
,(N'GI', N'GIB', N'Gibraltar', N'292')
,(N'GL', N'GRL', N'Greenland', N'304')
,(N'GM', N'GMB', N'Gambia', N'270')
,(N'GN', N'GIN', N'Guinea', N'324')
,(N'GP', N'GLP', N'Guadeloupe', N'312')
,(N'GQ', N'GNQ', N'Equatorial Guinea', N'226')
,(N'GR', N'GRC', N'Greece', N'300')
,(N'GS', N'SGS', N'South Georgia and the South Sandwich Islands', N'239')
,(N'GT', N'GTM', N'Guatemala', N'320')
,(N'GU', N'GUM', N'Guam', N'316')
,(N'GW', N'GNB', N'Guinea-Bissau', N'624')
,(N'GY', N'GUY', N'Guyana', N'328')
,(N'HK', N'HKG', N'Hong Kong', N'344')
,(N'HM', N'HMD', N'Heard Island and McDonald Islands', N'334')
,(N'HN', N'HND', N'Honduras', N'340')
,(N'HR', N'HRV', N'Croatia', N'191')
,(N'HT', N'HTI', N'Haiti', N'332')
,(N'HU', N'HUN', N'Hungary', N'348')
,(N'ID', N'IDN', N'Indonesia', N'360')
,(N'IE', N'IRL', N'Ireland', N'372')
,(N'IL', N'ISR', N'Israel', N'376')
,(N'IM', N'IMN', N'Isle of Man', N'833')
,(N'IN', N'IND', N'India', N'356')
,(N'IO', N'IOT', N'British Indian Ocean Territory', N'86 ')
,(N'IQ', N'IRQ', N'Iraq', N'368')
,(N'IR', N'IRN', N'Iran, Islamic Republic of', N'364')
,(N'IS', N'ISL', N'Iceland', N'352')
,(N'IT', N'ITA', N'Italy', N'380')
,(N'JE', N'JEY', N'Jersey', N'832')
,(N'JM', N'JAM', N'Jamaica', N'388')
,(N'JO', N'JOR', N'Jordan', N'400')
,(N'JP', N'JPN', N'Japan', N'392')
,(N'KE', N'KEN', N'Kenya', N'404')
,(N'KG', N'KGZ', N'Kyrgyzstan', N'417')
,(N'KH', N'KHM', N'Cambodia', N'116')
,(N'KI', N'KIR', N'Kiribati', N'296')
,(N'KM', N'COM', N'Comoros', N'174')
,(N'KN', N'KNA', N'Saint Kitts and Nevis', N'659')
,(N'KP', N'PRK', N'Korea, Democratic People''s Republic of', N'408')
,(N'KR', N'KOR', N'Korea, Republic of', N'410')
,(N'KW', N'KWT', N'Kuwait', N'414')
,(N'KY', N'CYM', N'Cayman Islands', N'136')
,(N'KZ', N'KAZ', N'Kazakhstan', N'398')
,(N'LA', N'LAO', N'Lao People''s Democratic Republic', N'418')
,(N'LB', N'LBN', N'Lebanon', N'422')
,(N'LC', N'LCA', N'Saint Lucia', N'662')
,(N'LI', N'LIE', N'Liechtenstein', N'438')
,(N'LK', N'LKA', N'Sri Lanka', N'144')
,(N'LR', N'LBR', N'Liberia', N'430')
,(N'LS', N'LSO', N'Lesotho', N'426')
,(N'LT', N'LTU', N'Lithuania', N'440')
,(N'LU', N'LUX', N'Luxembourg', N'442')
,(N'LV', N'LVA', N'Latvia', N'428')
,(N'LY', N'LBY', N'Libya', N'434')
,(N'MA', N'MAR', N'Morocco', N'504')
,(N'MC', N'MCO', N'Monaco', N'492')
,(N'MD', N'MDA', N'Moldova, Republic of', N'498')
,(N'ME', N'MNE', N'Montenegro', N'499')
,(N'MF', N'MAF', N'Saint Martin (French part)', N'663')
,(N'MG', N'MDG', N'Madagascar', N'450')
,(N'MH', N'MHL', N'Marshall Islands', N'584')
,(N'MK', N'MKD', N'Macedonia, the former Yugoslav Republic of', N'807')
,(N'ML', N'MLI', N'Mali', N'466')
,(N'MM', N'MMR', N'Myanmar', N'104')
,(N'MN', N'MNG', N'Mongolia', N'496')
,(N'MO', N'MAC', N'Macao', N'446')
,(N'MP', N'MNP', N'Northern Mariana Islands', N'580')
,(N'MQ', N'MTQ', N'Martinique', N'474')
,(N'MR', N'MRT', N'Mauritania', N'478')
,(N'MS', N'MSR', N'Montserrat', N'500')
,(N'MT', N'MLT', N'Malta', N'470')
,(N'MU', N'MUS', N'Mauritius', N'480')
,(N'MV', N'MDV', N'Maldives', N'462')
,(N'MW', N'MWI', N'Malawi', N'454')
,(N'MX', N'MEX', N'Mexico', N'484')
,(N'MY', N'MYS', N'Malaysia', N'458')
,(N'MZ', N'MOZ', N'Mozambique', N'508')
,(N'NA', N'NAM', N'Namibia', N'516')
,(N'NC', N'NCL', N'New Caledonia', N'540')
,(N'NE', N'NER', N'Niger', N'562')
,(N'NF', N'NFK', N'Norfolk Island', N'574')
,(N'NG', N'NGA', N'Nigeria', N'566')
,(N'NI', N'NIC', N'Nicaragua', N'558')
,(N'NL', N'NLD', N'Netherlands', N'528')
,(N'NO', N'NOR', N'Norway', N'578')
,(N'NP', N'NPL', N'Nepal', N'524')
,(N'NR', N'NRU', N'Nauru', N'520')
,(N'NU', N'NIU', N'Niue', N'570')
,(N'NZ', N'NZL', N'New Zealand', N'554')
,(N'OM', N'OMN', N'Oman', N'512')
,(N'PA', N'PAN', N'Panama', N'591')
,(N'PE', N'PER', N'Peru', N'604')
,(N'PF', N'PYF', N'French Polynesia', N'258')
,(N'PG', N'PNG', N'Papua New Guinea', N'598')
,(N'PH', N'PHL', N'Philippines', N'608')
,(N'PK', N'PAK', N'Pakistan', N'586')
,(N'PL', N'POL', N'Poland', N'616')
,(N'PM', N'SPM', N'Saint Pierre and Miquelon', N'666')
,(N'PN', N'PCN', N'Pitcairn', N'612')
,(N'PR', N'PRI', N'Puerto Rico', N'630')
,(N'PS', N'PSE', N'Palestine, State of', N'275')
,(N'PT', N'PRT', N'Portugal', N'620')
,(N'PW', N'PLW', N'Palau', N'585')
,(N'PY', N'PRY', N'Paraguay', N'600')
,(N'QA', N'QAT', N'Qatar', N'634')
,(N'RE', N'REU', N'Réunion', N'638')
,(N'RO', N'ROU', N'Romania', N'642')
,(N'RS', N'SRB', N'Serbia', N'688')
,(N'RU', N'RUS', N'Russian Federation', N'643')
,(N'RW', N'RWA', N'Rwanda', N'646')
,(N'SA', N'SAU', N'Saudi Arabia', N'682')
,(N'SB', N'SLB', N'Solomon Islands', N'90 ')
,(N'SC', N'SYC', N'Seychelles', N'690')
,(N'SD', N'SDN', N'Sudan', N'729')
,(N'SE', N'SWE', N'Sweden', N'752')
,(N'SG', N'SGP', N'Singapore', N'702')
,(N'SH', N'SHN', N'Saint Helena, Ascension and Tristan da Cunha', N'654')
,(N'SI', N'SVN', N'Slovenia', N'705')
,(N'SJ', N'SJM', N'Svalbard and Jan Mayen', N'744')
,(N'SK', N'SVK', N'Slovakia', N'703')
,(N'SL', N'SLE', N'Sierra Leone', N'694')
,(N'SM', N'SMR', N'San Marino', N'674')
,(N'SN', N'SEN', N'Senegal', N'686')
,(N'SO', N'SOM', N'Somalia', N'706')
,(N'SR', N'SUR', N'Suriname', N'740')
,(N'SS', N'SSD', N'South Sudan', N'728')
,(N'ST', N'STP', N'Sao Tome and Principe', N'678')
,(N'SV', N'SLV', N'El Salvador', N'222')
,(N'SX', N'SXM', N'Sint Maarten (Dutch part)', N'534')
,(N'SY', N'SYR', N'Syrian Arab Republic', N'760')
,(N'SZ', N'SWZ', N'Swaziland', N'748')
,(N'TC', N'TCA', N'Turks and Caicos Islands', N'796')
,(N'TD', N'TCD', N'Chad', N'148')
,(N'TF', N'ATF', N'French Southern Territories', N'260')
,(N'TG', N'TGO', N'Togo', N'768')
,(N'TH', N'THA', N'Thailand', N'764')
,(N'TJ', N'TJK', N'Tajikistan', N'762')
,(N'TK', N'TKL', N'Tokelau', N'772')
,(N'TL', N'TLS', N'Timor-Leste', N'626')
,(N'TM', N'TKM', N'Turkmenistan', N'795')
,(N'TN', N'TUN', N'Tunisia', N'788')
,(N'TO', N'TON', N'Tonga', N'776')
,(N'TR', N'TUR', N'Turkey', N'792')
,(N'TT', N'TTO', N'Trinidad and Tobago', N'780')
,(N'TV', N'TUV', N'Tuvalu', N'798')
,(N'TW', N'TWN', N'Taiwan, Province of China', N'158')
,(N'TZ', N'TZA', N'Tanzania, United Republic of', N'834')
,(N'UA', N'UKR', N'Ukraine', N'804')
,(N'UG', N'UGA', N'Uganda', N'800')
,(N'UM', N'UMI', N'United States Minor Outlying Islands', N'581')
,(N'US', N'USA', N'United States', N'840')
,(N'UY', N'URY', N'Uruguay', N'858')
,(N'UZ', N'UZB', N'Uzbekistan', N'860')
,(N'VA', N'VAT', N'Holy See (Vatican City State)', N'336')
,(N'VC', N'VCT', N'Saint Vincent and the Grenadines', N'670')
,(N'VE', N'VEN', N'Venezuela, Bolivarian Republic of', N'862')
,(N'VG', N'VGB', N'Virgin Islands, British', N'92 ')
,(N'VI', N'VIR', N'Virgin Islands, U.S.', N'850')
,(N'VN', N'VNM', N'Viet Nam', N'704')
,(N'VU', N'VUT', N'Vanuatu', N'548')
,(N'WF', N'WLF', N'Wallis and Futuna', N'876')
,(N'WS', N'WSM', N'Samoa', N'882')
,(N'YE', N'YEM', N'Yemen', N'887')
,(N'YT', N'MYT', N'Mayotte', N'175')
,(N'ZA', N'ZAF', N'South Africa', N'710')
,(N'ZM', N'ZMB', N'Zambia', N'894')
,(N'ZW', N'ZWE', N'Zimbabwe', N'716')
GO

INSERT INTO [StaticModel].[MimeTypes] ([FileExtension],[Name],[ContentType]) VALUES
('3dml' , 'In3D - 3DML' , 'text/vnd.in3d.3dml')
,('3g2' , '3GP2' , 'video/3gpp2')
,('3gp' , '3GP' , 'video/3gpp')
,('7z' , '7-Zip' , 'application/x-7z-compressed')
,('aab' , 'Adobe (Macropedia) Authorware - Binary File' , 'application/x-authorware-bin')
,('aac' , 'Advanced Audio Coding (AAC)' , 'audio/x-aac')
,('aam' , 'Adobe (Macropedia) Authorware - Map' , 'application/x-authorware-map')
,('aas' , 'Adobe (Macropedia) Authorware - Segment File' , 'application/x-authorware-seg')
,('abw' , 'AbiWord' , 'application/x-abiword')
,('ac' , 'Attribute Certificate' , 'application/pkix-attr-cert')
,('acc' , 'Active Content Compression' , 'application/vnd.americandynamics.acc')
,('ace' , 'Ace Archive' , 'application/x-ace-compressed')
,('acu' , 'ACU Cobol' , 'application/vnd.acucobol')
,('adp' , 'Adaptive differential pulse-code modulation' , 'audio/adpcm')
,('aep' , 'Audiograph' , 'application/vnd.audiograph')
,('afp' , 'MO:DCA-P' , 'application/vnd.ibm.modcap')
,('ahead' , 'Ahead AIR Application' , 'application/vnd.ahead.space')
,('ai' , 'PostScript' , 'application/postscript')
,('aif' , 'Audio Interchange File Format' , 'audio/x-aiff')
,('air' , 'Adobe AIR Application' , 'application/vnd.adobe.air-application-installer-package+zip')
,('ait' , 'Digital Video Broadcasting' , 'application/vnd.dvb.ait')
,('ami' , 'AmigaDE' , 'application/vnd.amiga.ami')
,('apk' , 'Android Package Archive' , 'application/vnd.android.package-archive')
,('application' , 'Microsoft ClickOnce' , 'application/x-ms-application')
,('apr' , 'Lotus Approach' , 'application/vnd.lotus-approach')
,('asf' , 'Microsoft Advanced Systems Format (ASF)' , 'video/x-ms-asf')
,('aso' , 'Simply Accounting' , 'application/vnd.accpac.simply.aso')
,('atc' , 'ACU Cobol' , 'application/vnd.acucorp')
,('atom, .xml' , 'Atom Syndication Format' , 'application/atom+xml')
,('atomcat' , 'Atom Publishing Protocol' , 'application/atomcat+xml')
,('atomsvc' , 'Atom Publishing Protocol Service Document' , 'application/atomsvc+xml')
,('atx' , 'Antix Game Player' , 'application/vnd.antix.game-component')
,('au' , 'Sun Audio - Au file format' , 'audio/basic')
,('avi' , 'Audio Video Interleave (AVI)' , 'video/x-msvideo')
,('aw' , 'Applixware' , 'application/applixware')
,('azf' , 'AirZip FileSECURE' , 'application/vnd.airzip.filesecure.azf')
,('azs' , 'AirZip FileSECURE' , 'application/vnd.airzip.filesecure.azs')
,('azw' , 'Amazon Kindle eBook format' , 'application/vnd.amazon.ebook')
,('bcpio' , 'Binary CPIO Archive' , 'application/x-bcpio')
,('bdf' , 'Glyph Bitmap Distribution Format' , 'application/x-font-bdf')
,('bdm' , 'SyncML - Device Management' , 'application/vnd.syncml.dm+wbxml')
,('bed' , 'RealVNC' , 'application/vnd.realvnc.bed')
,('bh2' , 'Fujitsu Oasys' , 'application/vnd.fujitsu.oasysprs')
,('bin' , 'Binary Data' , 'application/octet-stream')
,('bmi' , 'BMI Drawing Data Interchange' , 'application/vnd.bmi')
,('bmp' , 'Bitmap Image File' , 'image/bmp')
,('box' , 'Preview Systems ZipLock/VBox' , 'application/vnd.previewsystems.box')
,('btif' , 'BTIF' , 'image/prs.btif')
,('bz' , 'Bzip Archive' , 'application/x-bzip')
,('bz2' , 'Bzip2 Archive' , 'application/x-bzip2')
,('c' , 'C Source File' , 'text/x-c')
,('c11amc' , 'ClueTrust CartoMobile - Config' , 'application/vnd.cluetrust.cartomobile-config')
,('c11amz' , 'ClueTrust CartoMobile - Config Package' , 'application/vnd.cluetrust.cartomobile-config-pkg')
,('c4g' , 'Clonk Game' , 'application/vnd.clonk.c4group')
,('cab' , 'Microsoft Cabinet File' , 'application/vnd.ms-cab-compressed')
,('car' , 'CURL Applet' , 'application/vnd.curl.car')
,('cat' , 'Microsoft Trust UI Provider - Security Catalog' , 'application/vnd.ms-pki.seccat')
,('ccxml' , 'Voice Browser Call Control' , 'application/ccxml+xml,')
,('cdbcmsg' , 'CIM Database' , 'application/vnd.contact.cmsg')
,('cdkey' , 'MediaRemote' , 'application/vnd.mediastation.cdkey')
,('cdmia' , 'Cloud Data Management Interface (CDMI) - Capability' , 'application/cdmi-capability')
,('cdmic' , 'Cloud Data Management Interface (CDMI) - Contaimer' , 'application/cdmi-container')
,('cdmid' , 'Cloud Data Management Interface (CDMI) - Domain' , 'application/cdmi-domain')
,('cdmio' , 'Cloud Data Management Interface (CDMI) - Object' , 'application/cdmi-object')
,('cdmiq' , 'Cloud Data Management Interface (CDMI) - Queue' , 'application/cdmi-queue')
,('cdx' , 'ChemDraw eXchange file' , 'chemical/x-cdx')
,('cdxml' , 'CambridgeSoft Chem Draw' , 'application/vnd.chemdraw+xml')
,('cdy' , 'Interactive Geometry Software Cinderella' , 'application/vnd.cinderella')
,('cer' , 'Internet Public Key Infrastructure - Certificate' , 'application/pkix-cert')
,('cgm' , 'Computer Graphics Metafile' , 'image/cgm')
,('chat' , 'pIRCh' , 'application/x-chat')
,('chm' , 'Microsoft Html Help File' , 'application/vnd.ms-htmlhelp')
,('chrt' , 'KDE KOffice Office Suite - KChart' , 'application/vnd.kde.kchart')
,('cif' , 'Crystallographic Interchange Format' , 'chemical/x-cif')
,('cii' , 'ANSER-WEB Terminal Client - Certificate Issue' , 'application/vnd.anser-web-certificate-issue-initiation')
,('cil' , 'Microsoft Artgalry' , 'application/vnd.ms-artgalry')
,('cla' , 'Claymore Data Files' , 'application/vnd.claymore')
,('class' , 'Java Bytecode File' , 'application/java-vm')
,('clkk' , 'CrickSoftware - Clicker - Keyboard' , 'application/vnd.crick.clicker.keyboard')
,('clkp' , 'CrickSoftware - Clicker - Palette' , 'application/vnd.crick.clicker.palette')
,('clkt' , 'CrickSoftware - Clicker - Template' , 'application/vnd.crick.clicker.template')
,('clkw' , 'CrickSoftware - Clicker - Wordbank' , 'application/vnd.crick.clicker.wordbank')
,('clkx' , 'CrickSoftware - Clicker' , 'application/vnd.crick.clicker')
,('clp' , 'Microsoft Clipboard Clip' , 'application/x-msclip')
,('cmc' , 'CosmoCaller' , 'application/vnd.cosmocaller')
,('cmdf' , 'CrystalMaker Data Format' , 'chemical/x-cmdf')
,('cml' , 'Chemical Markup Language' , 'chemical/x-cml')
,('cmp' , 'CustomMenu' , 'application/vnd.yellowriver-custom-menu')
,('cmx' , 'Corel Metafile Exchange (CMX)' , 'image/x-cmx')
,('cod' , 'Blackberry COD File' , 'application/vnd.rim.cod')
,('cpio' , 'CPIO Archive' , 'application/x-cpio')
,('cpt' , 'Compact Pro' , 'application/mac-compactpro')
,('crd' , 'Microsoft Information Card' , 'application/x-mscardfile')
,('crl' , 'Internet Public Key Infrastructure - Certificate Revocation Lists' , 'application/pkix-crl')
,('cryptonote' , 'CryptoNote' , 'application/vnd.rig.cryptonote')
,('csh' , 'C Shell Script' , 'application/x-csh')
,('csml' , 'Chemical Style Markup Language' , 'chemical/x-csml')
,('csp' , 'Sixth Floor Media - CommonSpace' , 'application/vnd.commonspace')
,('css' , 'Cascading Style Sheets (CSS)' , 'text/css')
,('csv' , 'Comma-Seperated Values' , 'text/csv')
,('cu' , 'CU-SeeMe' , 'application/cu-seeme')
,('curl' , 'Curl - Applet' , 'text/vnd.curl')
,('cww' , 'CU-Writer' , 'application/prs.cww')
,('dae' , 'COLLADA' , 'model/vnd.collada+xml')
,('daf' , 'Mobius Management Systems - UniversalArchive' , 'application/vnd.mobius.daf')
,('davmount' , 'Web Distributed Authoring and Versioning' , 'application/davmount+xml')
,('dcurl' , 'Curl - Detached Applet' , 'text/vnd.curl.dcurl')
,('dd2' , 'OMA Download Agents' , 'application/vnd.oma.dd2+xml')
,('ddd' , 'Fujitsu - Xerox 2D CAD Data' , 'application/vnd.fujixerox.ddd')
,('deb' , 'Debian Package' , 'application/x-debian-package')
,('der' , 'X.509 Certificate' , 'application/x-x509-ca-cert')
,('dfac' , 'DreamFactory' , 'application/vnd.dreamfactory')
,('dir' , 'Adobe Shockwave Player' , 'application/x-director')
,('dis' , 'Mobius Management Systems - Distribution Database' , 'application/vnd.mobius.dis')
,('djvu' , 'DjVu' , 'image/vnd.djvu')
,('dna' , 'New Moon Liftoff/DNA' , 'application/vnd.dna')
,('doc' , 'Microsoft Word' , 'application/msword')
,('docm' , 'Microsoft Word - Macro-Enabled Document' , 'application/vnd.ms-word.document.macroenabled.12')
,('docx' , 'Microsoft Office - OOXML - Word Document' , 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
,('dotm' , 'Microsoft Word - Macro-Enabled Template' , 'application/vnd.ms-word.template.macroenabled.12')
,('dotx' , 'Microsoft Office - OOXML - Word Document Template' , 'application/vnd.openxmlformats-officedocument.wordprocessingml.template')
,('dp' , 'OSGi Deployment Package' , 'application/vnd.osgi.dp')
,('dpg' , 'DPGraph' , 'application/vnd.dpgraph')
,('dra' , 'DRA Audio' , 'audio/vnd.dra')
,('dsc' , 'PRS Lines Tag' , 'text/prs.lines.tag')
,('dssc' , 'Data Structure for the Security Suitability of Cryptographic Algorithms' , 'application/dssc+der')
,('dtb' , 'Digital Talking Book' , 'application/x-dtbook+xml')
,('dtd' , 'Document Type Definition' , 'application/xml-dtd')
,('dts' , 'DTS Audio' , 'audio/vnd.dts')
,('dtshd' , 'DTS High Definition Audio' , 'audio/vnd.dts.hd')
,('dvi' , 'Device Independent File Format (DVI)' , 'application/x-dvi')
,('dwf' , 'Autodesk Design Web Format (DWF)' , 'model/vnd.dwf')
,('dwg' , 'DWG Drawing' , 'image/vnd.dwg')
,('dxf' , 'AutoCAD DXF' , 'image/vnd.dxf')
,('dxp' , 'TIBCO Spotfire' , 'application/vnd.spotfire.dxp')
,('ecelp4800' , 'Nuera ECELP 4800' , 'audio/vnd.nuera.ecelp4800')
,('ecelp7470' , 'Nuera ECELP 7470' , 'audio/vnd.nuera.ecelp7470')
,('ecelp9600' , 'Nuera ECELP 9600' , 'audio/vnd.nuera.ecelp9600')
,('edm' , 'Novadigm''s RADIA and EDM products' , 'application/vnd.novadigm.edm')
,('edx' , 'Novadigm''s RADIA and EDM products' , 'application/vnd.novadigm.edx')
,('efif' , 'Pcsel eFIF File' , 'application/vnd.picsel')
,('ei6' , 'Proprietary P&G Standard Reporting System' , 'application/vnd.pg.osasli')
,('eml' , 'Email Message' , 'message/rfc822')
,('emma' , 'Extensible MultiModal Annotation' , 'application/emma+xml')
,('eol' , 'Digital Winds Music' , 'audio/vnd.digital-winds')
,('eot' , 'Microsoft Embedded OpenType' , 'application/vnd.ms-fontobject')
,('epub' , 'Electronic Publication' , 'application/epub+zip')
,('es' , 'ECMAScript' , 'application/ecmascript')
,('es3' , 'MICROSEC e-Szign¢' , 'application/vnd.eszigno3+xml')
,('esf' , 'QUASS Stream Player' , 'application/vnd.epson.esf')
,('etx' , 'Setext' , 'text/x-setext')
,('exe' , 'Microsoft Application' , 'application/x-msdownload')
,('exi' , 'Efficient XML Interchange' , 'application/exi')
,('ext' , 'Novadigm''s RADIA and EDM products' , 'application/vnd.novadigm.ext')
,('ez2' , 'EZPix Secure Photo Album' , 'application/vnd.ezpix-album')
,('ez3' , 'EZPix Secure Photo Album' , 'application/vnd.ezpix-package')
,('f' , 'Fortran Source File' , 'text/x-fortran')
,('f4v' , 'Flash Video' , 'video/x-f4v')
,('fbs' , 'FastBid Sheet' , 'image/vnd.fastbidsheet')
,('fcs' , 'International Society for Advancement of Cytometry' , 'application/vnd.isac.fcs')
,('fdf' , 'Forms Data Format' , 'application/vnd.fdf')
,('fe_launch' , 'FCS Express Layout Link' , 'application/vnd.denovo.fcselayout-link')
,('fg5' , 'Fujitsu Oasys' , 'application/vnd.fujitsu.oasysgp')
,('fh' , 'FreeHand MX' , 'image/x-freehand')
,('fig' , 'Xfig' , 'application/x-xfig')
,('fli' , 'FLI/FLC Animation Format' , 'video/x-fli')
,('flo' , 'Micrografx' , 'application/vnd.micrografx.flo')
,('flv' , 'Flash Video' , 'video/x-flv')
,('flw' , 'KDE KOffice Office Suite - Kivio' , 'application/vnd.kde.kivio')
,('flx' , 'FLEXSTOR' , 'text/vnd.fmi.flexstor')
,('fly' , 'mod_fly / fly.cgi' , 'text/vnd.fly')
,('fm' , 'FrameMaker Normal Format' , 'application/vnd.framemaker')
,('fnc' , 'Frogans Player' , 'application/vnd.frogans.fnc')
,('fpx' , 'FlashPix' , 'image/vnd.fpx')
,('fsc' , 'Friendly Software Corporation' , 'application/vnd.fsc.weblaunch')
,('fst' , 'FAST Search & Transfer ASA' , 'image/vnd.fst')
,('ftc' , 'FluxTime Clip' , 'application/vnd.fluxtime.clip')
,('fti' , 'ANSER-WEB Terminal Client - Web Funds Transfer' , 'application/vnd.anser-web-funds-transfer-initiation')
,('fvt' , 'FAST Search & Transfer ASA' , 'video/vnd.fvt')
,('fxp' , 'Adobe Flex Project' , 'application/vnd.adobe.fxp')
,('fzs' , 'FuzzySheet' , 'application/vnd.fuzzysheet')
,('g2w' , 'GeoplanW' , 'application/vnd.geoplan')
,('g3' , 'G3 Fax Image' , 'image/g3fax')
,('g3w' , 'GeospacW' , 'application/vnd.geospace')
,('gac' , 'Groove - Account' , 'application/vnd.groove-account')
,('gdl' , 'Geometric Description Language (GDL)' , 'model/vnd.gdl')
,('geo' , 'DynaGeo' , 'application/vnd.dynageo')
,('gex' , 'GeoMetry Explorer' , 'application/vnd.geometry-explorer')
,('ggb' , 'GeoGebra' , 'application/vnd.geogebra.file')
,('ggt' , 'GeoGebra' , 'application/vnd.geogebra.tool')
,('ghf' , 'Groove - Help' , 'application/vnd.groove-help')
,('gif' , 'Graphics Interchange Format' , 'image/gif')
,('gim' , 'Groove - Identity Message' , 'application/vnd.groove-identity-message')
,('gmx' , 'GameMaker ActiveX' , 'application/vnd.gmx')
,('gnumeric' , 'Gnumeric' , 'application/x-gnumeric')
,('gph' , 'NpGraphIt' , 'application/vnd.flographit')
,('gqf' , 'GrafEq' , 'application/vnd.grafeq')
,('gram' , 'Speech Recognition Grammar Specification' , 'application/srgs')
,('grv' , 'Groove - Injector' , 'application/vnd.groove-injector')
,('grxml' , 'Speech Recognition Grammar Specification - XML' , 'application/srgs+xml')
,('gsf' , 'Ghostscript Font' , 'application/x-font-ghostscript')
,('gtar' , 'GNU Tar Files' , 'application/x-gtar')
,('gtm' , 'Groove - Tool Message' , 'application/vnd.groove-tool-message')
,('gtw' , 'Gen-Trix Studio' , 'model/vnd.gtw')
,('gv' , 'Graphviz' , 'text/vnd.graphviz')
,('gxt' , 'GEONExT and JSXGraph' , 'application/vnd.geonext')
,('h261' , 'H.261' , 'video/h261')
,('h263' , 'H.263' , 'video/h263')
,('h264' , 'H.264' , 'video/h264')
,('hal' , 'Hypertext Application Language' , 'application/vnd.hal+xml')
,('hbci' , 'Homebanking Computer Interface (HBCI)' , 'application/vnd.hbci')
,('hdf' , 'Hierarchical Data Format' , 'application/x-hdf')
,('hlp' , 'WinHelp' , 'application/winhlp')
,('hpgl' , 'HP-GL/2 and HP RTL' , 'application/vnd.hp-hpgl')
,('hpid' , 'Hewlett Packard Instant Delivery' , 'application/vnd.hp-hpid')
,('hps' , 'Hewlett-Packard''s WebPrintSmart' , 'application/vnd.hp-hps')
,('hqx' , 'Macintosh BinHex 4.0' , 'application/mac-binhex40')
,('htke' , 'Kenamea App' , 'application/vnd.kenameaapp')
,('html' , 'HyperText Markup Language (HTML)' , 'text/html')
,('hvd' , 'HV Voice Dictionary' , 'application/vnd.yamaha.hv-dic')
,('hvp' , 'HV Voice Parameter' , 'application/vnd.yamaha.hv-voice')
,('hvs' , 'HV Script' , 'application/vnd.yamaha.hv-script')
,('i2g' , 'Interactive Geometry Software' , 'application/vnd.intergeo')
,('icc' , 'ICC profile' , 'application/vnd.iccprofile')
,('ice' , 'CoolTalk' , 'x-conference/x-cooltalk')
,('ico' , 'Icon Image' , 'image/x-icon')
,('ics' , 'iCalendar' , 'text/calendar')
,('ief' , 'Image Exchange Format' , 'image/ief')
,('ifm' , 'Shana Informed Filler' , 'application/vnd.shana.informed.formdata')
,('igl' , 'igLoader' , 'application/vnd.igloader')
,('igm' , 'IOCOM Visimeet' , 'application/vnd.insors.igm')
,('igs' , 'Initial Graphics Exchange Specification (IGES)' , 'model/iges')
,('igx' , 'Micrografx iGrafx Professional' , 'application/vnd.micrografx.igx')
,('iif' , 'Shana Informed Filler' , 'application/vnd.shana.informed.interchange')
,('imp' , 'Simply Accounting - Data Import' , 'application/vnd.accpac.simply.imp')
,('ims' , 'Microsoft Class Server' , 'application/vnd.ms-ims')
,('ipfix' , 'Internet Protocol Flow Information Export' , 'application/ipfix')
,('ipk' , 'Shana Informed Filler' , 'application/vnd.shana.informed.package')
,('irm' , 'IBM DB2 Rights Manager' , 'application/vnd.ibm.rights-management')
,('irp' , 'iRepository / Lucidoc Editor' , 'application/vnd.irepository.package+xml')
,('itp' , 'Shana Informed Filler' , 'application/vnd.shana.informed.formtemplate')
,('ivp' , 'ImmerVision PURE Players' , 'application/vnd.immervision-ivp')
,('ivu' , 'ImmerVision PURE Players' , 'application/vnd.immervision-ivu')
,('jad' , 'J2ME App Descriptor' , 'text/vnd.sun.j2me.app-descriptor')
,('jam' , 'Lightspeed Audio Lab' , 'application/vnd.jam')
,('jar' , 'Java Archive' , 'application/java-archive')
,('java' , 'Java Source File' , 'text/x-java-source,java')
,('jisp' , 'RhymBox' , 'application/vnd.jisp')
,('jlt' , 'HP Indigo Digital Press - Job Layout Languate' , 'application/vnd.hp-jlyt')
,('jnlp' , 'Java Network Launching Protocol' , 'application/x-java-jnlp-file')
,('joda' , 'Joda Archive' , 'application/vnd.joost.joda-archive')
,('jpeg, .jpg' , 'JPEG Image' , 'image/jpeg')
,('jpeg, .jpg' , 'JPEG Image (Citrix client)' , 'image/x-citrix-jpeg')
,('jpgv' , 'JPGVideo' , 'video/jpeg')
,('jpm' , 'JPEG 2000 Compound Image File Format' , 'video/jpm')
,('js' , 'JavaScript' , 'application/javascript')
,('json' , 'JavaScript Object Notation (JSON)' , 'application/json')
,('karbon' , 'KDE KOffice Office Suite - Karbon' , 'application/vnd.kde.karbon')
,('kfo' , 'KDE KOffice Office Suite - Kformula' , 'application/vnd.kde.kformula')
,('kia' , 'Kidspiration' , 'application/vnd.kidspiration')
,('kml' , 'Google Earth - KML' , 'application/vnd.google-earth.kml+xml')
,('kmz' , 'Google Earth - Zipped KML' , 'application/vnd.google-earth.kmz')
,('kne' , 'Kinar Applications' , 'application/vnd.kinar')
,('kon' , 'KDE KOffice Office Suite - Kontour' , 'application/vnd.kde.kontour')
,('kpr' , 'KDE KOffice Office Suite - Kpresenter' , 'application/vnd.kde.kpresenter')
,('ksp' , 'KDE KOffice Office Suite - Kspread' , 'application/vnd.kde.kspread')
,('ktx' , 'OpenGL Textures (KTX)' , 'image/ktx')
,('ktz' , 'Kahootz' , 'application/vnd.kahootz')
,('kwd' , 'KDE KOffice Office Suite - Kword' , 'application/vnd.kde.kword')
,('lasxml' , 'Laser App Enterprise' , 'application/vnd.las.las+xml')
,('latex' , 'LaTeX' , 'application/x-latex')
,('lbd' , 'Life Balance - Desktop Edition' , 'application/vnd.llamagraphics.life-balance.desktop')
,('lbe' , 'Life Balance - Exchange Format' , 'application/vnd.llamagraphics.life-balance.exchange+xml')
,('les' , 'Archipelago Lesson Player' , 'application/vnd.hhe.lesson-player')
,('link66' , 'ROUTE 66 Location Based Services' , 'application/vnd.route66.link66+xml')
,('lrm' , 'Microsoft Learning Resource Module' , 'application/vnd.ms-lrm')
,('ltf' , 'Frogans Player' , 'application/vnd.frogans.ltf')
,('lvp' , 'Lucent Voice' , 'audio/vnd.lucent.voice')
,('lwp' , 'Lotus Wordpro' , 'application/vnd.lotus-wordpro')
,('m21' , 'MPEG-21' , 'application/mp21')
,('m3u' , 'M3U (Multimedia Playlist)' , 'audio/x-mpegurl')
,('m3u8' , 'Multimedia Playlist Unicode' , 'application/vnd.apple.mpegurl')
,('m4v' , 'M4v' , 'video/x-m4v')
,('ma' , 'Mathematica Notebooks' , 'application/mathematica')
,('mads' , 'Metadata Authority Description Schema' , 'application/mads+xml')
,('mag' , 'EcoWin Chart' , 'application/vnd.ecowin.chart')
,('mathml' , 'Mathematical Markup Language' , 'application/mathml+xml')
,('mbk' , 'Mobius Management Systems - Basket file' , 'application/vnd.mobius.mbk')
,('mbox' , 'Mbox database files' , 'application/mbox')
,('mc1' , 'MedCalc' , 'application/vnd.medcalcdata')
,('mcd' , 'Micro CADAM Helix D&D' , 'application/vnd.mcd')
,('mcurl' , 'Curl - Manifest File' , 'text/vnd.curl.mcurl')
,('mdb' , 'Microsoft Access' , 'application/x-msaccess')
,('mdi' , 'Microsoft Document Imaging Format' , 'image/vnd.ms-modi')
,('meta4' , 'Metalink' , 'application/metalink4+xml')
,('mets' , 'Metadata Encoding and Transmission Standard' , 'application/mets+xml')
,('mfm' , 'Melody Format for Mobile Platform' , 'application/vnd.mfmp')
,('mgp' , 'MapGuide DBXML' , 'application/vnd.osgeo.mapguide.package')
,('mgz' , 'EFI Proteus' , 'application/vnd.proteus.magazine')
,('mid' , 'MIDI - Musical Instrument Digital Interface' , 'audio/midi')
,('mif' , 'FrameMaker Interchange Format' , 'application/vnd.mif')
,('mj2' , 'Motion JPEG 2000' , 'video/mj2')
,('mlp' , 'Dolby Meridian Lossless Packing' , 'application/vnd.dolby.mlp')
,('mmd' , 'Karaoke on Chipnuts Chipsets' , 'application/vnd.chipnuts.karaoke-mmd')
,('mmf' , 'SMAF File' , 'application/vnd.smaf')
,('mmr' , 'EDMICS 2000' , 'image/vnd.fujixerox.edmics-mmr')
,('mny' , 'Microsoft Money' , 'application/x-msmoney')
,('mods' , 'Metadata Object Description Schema' , 'application/mods+xml')
,('movie' , 'SGI Movie' , 'video/x-sgi-movie')
,('mp4' , 'MPEG-4 Video' , 'video/mp4')
,('mp4' , 'MPEG4' , 'application/mp4')
,('mp4a' , 'MPEG-4 Audio' , 'audio/mp4')
,('mpc' , 'Mophun Certificate' , 'application/vnd.mophun.certificate')
,('mpeg' , 'MPEG Video' , 'video/mpeg')
,('mpga' , 'MPEG Audio' , 'audio/mpeg')
,('mpkg' , 'Apple Installer Package' , 'application/vnd.apple.installer+xml')
,('mpm' , 'Blueice Research Multipass' , 'application/vnd.blueice.multipass')
,('mpn' , 'Mophun VM' , 'application/vnd.mophun.application')
,('mpp' , 'Microsoft Project' , 'application/vnd.ms-project')
,('mpy' , 'MiniPay' , 'application/vnd.ibm.minipay')
,('mqy' , 'Mobius Management Systems - Query File' , 'application/vnd.mobius.mqy')
,('mrc' , 'MARC Formats' , 'application/marc')
,('mrcx' , 'MARC21 XML Schema' , 'application/marcxml+xml')
,('mscml' , 'Media Server Control Markup Language' , 'application/mediaservercontrol+xml')
,('mseq' , '3GPP MSEQ File' , 'application/vnd.mseq')
,('msf' , 'QUASS Stream Player' , 'application/vnd.epson.msf')
,('msg' , 'Microsoft Outlook' , 'application/vnd.ms-outlook')
,('msh' , 'Mesh Data Type' , 'model/mesh')
,('msl' , 'Mobius Management Systems - Script Language' , 'application/vnd.mobius.msl')
,('msty' , 'Muvee Automatic Video Editing' , 'application/vnd.muvee.style')
,('mts' , 'Virtue MTS' , 'model/vnd.mts')
,('mus' , 'MUsical Score Interpreted Code Invented for the ASCII designation of Notation' , 'application/vnd.musician')
,('musicxml' , 'Recordare Applications' , 'application/vnd.recordare.musicxml+xml')
,('mvb' , 'Microsoft MediaView' , 'application/x-msmediaview')
,('mwf' , 'Medical Waveform Encoding Format' , 'application/vnd.mfer')
,('mxf' , 'Material Exchange Format' , 'application/mxf')
,('mxl' , 'Recordare Applications' , 'application/vnd.recordare.musicxml')
,('mxml' , 'MXML' , 'application/xv+xml')
,('mxs' , 'Triscape Map Explorer' , 'application/vnd.triscape.mxs')
,('mxu' , 'MPEG Url' , 'video/vnd.mpegurl')
,('n-gage' , 'N-Gage Game Installer' , 'application/vnd.nokia.n-gage.symbian.install')
,('n3' , 'Notation3' , 'text/n3')
,('nbp' , 'Mathematica Notebook Player' , 'application/vnd.wolfram.player')
,('nc' , 'Network Common Data Form (NetCDF)' , 'application/x-netcdf')
,('ncx' , 'Navigation Control file for XML (for ePub)' , 'application/x-dtbncx+xml')
,('ngdat' , 'N-Gage Game Data' , 'application/vnd.nokia.n-gage.data')
,('nlu' , 'neuroLanguage' , 'application/vnd.neurolanguage.nlu')
,('nml' , 'Enliven Viewer' , 'application/vnd.enliven')
,('nnd' , 'NobleNet Directory' , 'application/vnd.noblenet-directory')
,('nns' , 'NobleNet Sealer' , 'application/vnd.noblenet-sealer')
,('nnw' , 'NobleNet Web' , 'application/vnd.noblenet-web')
,('npx' , 'FlashPix' , 'image/vnd.net-fpx')
,('nsf' , 'Lotus Notes' , 'application/vnd.lotus-notes')
,('oa2' , 'Fujitsu Oasys' , 'application/vnd.fujitsu.oasys2')
,('oa3' , 'Fujitsu Oasys' , 'application/vnd.fujitsu.oasys3')
,('oas' , 'Fujitsu Oasys' , 'application/vnd.fujitsu.oasys')
,('obd' , 'Microsoft Office Binder' , 'application/x-msbinder')
,('oda' , 'Office Document Architecture' , 'application/oda')
,('odb' , 'OpenDocument Database' , 'application/vnd.oasis.opendocument.database')
,('odc' , 'OpenDocument Chart' , 'application/vnd.oasis.opendocument.chart')
,('odf' , 'OpenDocument Formula' , 'application/vnd.oasis.opendocument.formula')
,('odft' , 'OpenDocument Formula Template' , 'application/vnd.oasis.opendocument.formula-template')
,('odg' , 'OpenDocument Graphics' , 'application/vnd.oasis.opendocument.graphics')
,('odi' , 'OpenDocument Image' , 'application/vnd.oasis.opendocument.image')
,('odm' , 'OpenDocument Text Master' , 'application/vnd.oasis.opendocument.text-master')
,('odp' , 'OpenDocument Presentation' , 'application/vnd.oasis.opendocument.presentation')
,('ods' , 'OpenDocument Spreadsheet' , 'application/vnd.oasis.opendocument.spreadsheet')
,('odt' , 'OpenDocument Text' , 'application/vnd.oasis.opendocument.text')
,('oga' , 'Ogg Audio' , 'audio/ogg')
,('ogv' , 'Ogg Video' , 'video/ogg')
,('ogx' , 'Ogg' , 'application/ogg')
,('onetoc' , 'Microsoft OneNote' , 'application/onenote')
,('opf' , 'Open eBook Publication Structure' , 'application/oebps-package+xml')
,('org' , 'Lotus Organizer' , 'application/vnd.lotus-organizer')
,('osf' , 'Open Score Format' , 'application/vnd.yamaha.openscoreformat')
,('osfpvg' , 'OSFPVG' , 'application/vnd.yamaha.openscoreformat.osfpvg+xml')
,('otc' , 'OpenDocument Chart Template' , 'application/vnd.oasis.opendocument.chart-template')
,('otf' , 'OpenType Font File' , 'application/x-font-otf')
,('otg' , 'OpenDocument Graphics Template' , 'application/vnd.oasis.opendocument.graphics-template')
,('oth' , 'Open Document Text Web' , 'application/vnd.oasis.opendocument.text-web')
,('oti' , 'OpenDocument Image Template' , 'application/vnd.oasis.opendocument.image-template')
,('otp' , 'OpenDocument Presentation Template' , 'application/vnd.oasis.opendocument.presentation-template')
,('ots' , 'OpenDocument Spreadsheet Template' , 'application/vnd.oasis.opendocument.spreadsheet-template')
,('ott' , 'OpenDocument Text Template' , 'application/vnd.oasis.opendocument.text-template')
,('oxt' , 'Open Office Extension' , 'application/vnd.openofficeorg.extension')
,('p' , 'Pascal Source File' , 'text/x-pascal')
,('p10' , 'PKCS #10 - Certification Request Standard' , 'application/pkcs10')
,('p12' , 'PKCS #12 - Personal Information Exchange Syntax Standard' , 'application/x-pkcs12')
,('p7b' , 'PKCS #7 - Cryptographic Message Syntax Standard (Certificates)' , 'application/x-pkcs7-certificates')
,('p7m' , 'PKCS #7 - Cryptographic Message Syntax Standard' , 'application/pkcs7-mime')
,('p7r' , 'PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)' , 'application/x-pkcs7-certreqresp')
,('p7s' , 'PKCS #7 - Cryptographic Message Syntax Standard' , 'application/pkcs7-signature')
,('p8' , 'PKCS #8 - Private-Key Information Syntax Standard' , 'application/pkcs8')
,('par' , 'BAS Partitur Format' , 'text/plain-bas')
,('paw' , 'PawaaFILE' , 'application/vnd.pawaafile')
,('pbd' , 'PowerBuilder' , 'application/vnd.powerbuilder6')
,('pbm' , 'Portable Bitmap Format' , 'image/x-portable-bitmap')
,('pcf' , 'Portable Compiled Format' , 'application/x-font-pcf')
,('pcl' , 'HP Printer Command Language' , 'application/vnd.hp-pcl')
,('pclxl' , 'PCL 6 Enhanced (Formely PCL XL)' , 'application/vnd.hp-pclxl')
,('pcurl' , 'CURL Applet' , 'application/vnd.curl.pcurl')
,('pcx' , 'PCX Image' , 'image/x-pcx')
,('pdb' , 'PalmOS Data' , 'application/vnd.palm')
,('pdf' , 'Adobe Portable Document Format' , 'application/pdf')
,('pfa' , 'PostScript Fonts' , 'application/x-font-type1')
,('pfr' , 'Portable Font Resource' , 'application/font-tdpfr')
,('pgm' , 'Portable Graymap Format' , 'image/x-portable-graymap')
,('pgn' , 'Portable Game Notation (Chess Games)' , 'application/x-chess-pgn')
,('pgp' , 'Pretty Good Privacy' , 'application/pgp-encrypted')
,('pgp' , 'Pretty Good Privacy - Signature' , 'application/pgp-signature')
,('pic' , 'PICT Image' , 'image/x-pict')
,('pjpeg' , 'JPEG Image (Progressive)' , 'image/pjpeg')
,('pki' , 'Internet Public Key Infrastructure - Certificate Management Protocole' , 'application/pkixcmp')
,('pkipath' , 'Internet Public Key Infrastructure - Certification Path' , 'application/pkix-pkipath')
,('plb' , '3rd Generation Partnership Project - Pic Large' , 'application/vnd.3gpp.pic-bw-large')
,('plc' , 'Mobius Management Systems - Policy Definition Language File' , 'application/vnd.mobius.plc')
,('plf' , 'PocketLearn Viewers' , 'application/vnd.pocketlearn')
,('pls' , 'Pronunciation Lexicon Specification' , 'application/pls+xml')
,('pml' , 'PosML' , 'application/vnd.ctc-posml')
,('png' , 'Portable Network Graphics (PNG)' , 'image/png')
,('png' , 'Portable Network Graphics (PNG) (Citrix client)' , 'image/x-citrix-png')
,('png' , 'Portable Network Graphics (PNG) (x-token)' , 'image/x-png')
,('pnm' , 'Portable Anymap Image' , 'image/x-portable-anymap')
,('portpkg' , 'MacPorts Port System' , 'application/vnd.macports.portpkg')
,('potm' , 'Microsoft PowerPoint - Macro-Enabled Template File' , 'application/vnd.ms-powerpoint.template.macroenabled.12')
,('potx' , 'Microsoft Office - OOXML - Presentation Template' , 'application/vnd.openxmlformats-officedocument.presentationml.template')
,('ppam' , 'Microsoft PowerPoint - Add-in file' , 'application/vnd.ms-powerpoint.addin.macroenabled.12')
,('ppd' , 'Adobe PostScript Printer Description File Format' , 'application/vnd.cups-ppd')
,('ppm' , 'Portable Pixmap Format' , 'image/x-portable-pixmap')
,('ppsm' , 'Microsoft PowerPoint - Macro-Enabled Slide Show File' , 'application/vnd.ms-powerpoint.slideshow.macroenabled.12')
,('ppsx' , 'Microsoft Office - OOXML - Presentation (Slideshow)' , 'application/vnd.openxmlformats-officedocument.presentationml.slideshow')
,('ppt' , 'Microsoft PowerPoint' , 'application/vnd.ms-powerpoint')
,('pptm' , 'Microsoft PowerPoint - Macro-Enabled Presentation File' , 'application/vnd.ms-powerpoint.presentation.macroenabled.12')
,('pptx' , 'Microsoft Office - OOXML - Presentation' , 'application/vnd.openxmlformats-officedocument.presentationml.presentation')
,('prc' , 'Mobipocket' , 'application/x-mobipocket-ebook')
,('pre' , 'Lotus Freelance' , 'application/vnd.lotus-freelance')
,('prf' , 'PICSRules' , 'application/pics-rules')
,('psb' , '3rd Generation Partnership Project - Pic Small' , 'application/vnd.3gpp.pic-bw-small')
,('psd' , 'Photoshop Document' , 'image/vnd.adobe.photoshop')
,('psf' , 'PSF Fonts' , 'application/x-font-linux-psf')
,('pskcxml' , 'Portable Symmetric Key Container' , 'application/pskc+xml')
,('ptid' , 'Princeton Video Image' , 'application/vnd.pvi.ptid1')
,('pub' , 'Microsoft Publisher' , 'application/x-mspublisher')
,('pvb' , '3rd Generation Partnership Project - Pic Var' , 'application/vnd.3gpp.pic-bw-var')
,('pwn' , '3M Post It Notes' , 'application/vnd.3m.post-it-notes')
,('pya' , 'Microsoft PlayReady Ecosystem' , 'audio/vnd.ms-playready.media.pya')
,('pyv' , 'Microsoft PlayReady Ecosystem Video' , 'video/vnd.ms-playready.media.pyv')
,('qam' , 'QuickAnime Player' , 'application/vnd.epson.quickanime')
,('qbo' , 'Open Financial Exchange' , 'application/vnd.intu.qbo')
,('qfx' , 'Quicken' , 'application/vnd.intu.qfx')
,('qps' , 'PubliShare Objects' , 'application/vnd.publishare-delta-tree')
,('qt' , 'Quicktime Video' , 'video/quicktime')
,('qxd' , 'QuarkXpress' , 'application/vnd.quark.quarkxpress')
,('ram' , 'Real Audio Sound' , 'audio/x-pn-realaudio')
,('rar' , 'RAR Archive' , 'application/x-rar-compressed')
,('ras' , 'CMU Image' , 'image/x-cmu-raster')
,('rcprofile' , 'IP Unplugged Roaming Client' , 'application/vnd.ipunplugged.rcprofile')
,('rdf' , 'Resource Description Framework' , 'application/rdf+xml')
,('rdz' , 'RemoteDocs R-Viewer' , 'application/vnd.data-vision.rdz')
,('rep' , 'BusinessObjects' , 'application/vnd.businessobjects')
,('res' , 'Digital Talking Book - Resource File' , 'application/x-dtbresource+xml')
,('rgb' , 'Silicon Graphics RGB Bitmap' , 'image/x-rgb')
,('rif' , 'IMS Networks' , 'application/reginfo+xml')
,('rip' , 'Hit''n''Mix' , 'audio/vnd.rip')
,('rl' , 'XML Resource Lists' , 'application/resource-lists+xml')
,('rlc' , 'EDMICS 2000' , 'image/vnd.fujixerox.edmics-rlc')
,('rld' , 'XML Resource Lists Diff' , 'application/resource-lists-diff+xml')
,('rm' , 'RealMedia' , 'application/vnd.rn-realmedia')
,('rmp' , 'Real Audio Sound' , 'audio/x-pn-realaudio-plugin')
,('rms' , 'Mobile Information Device Profile' , 'application/vnd.jcp.javame.midlet-rms')
,('rnc' , 'Relax NG Compact Syntax' , 'application/relax-ng-compact-syntax')
,('rp9' , 'RetroPlatform Player' , 'application/vnd.cloanto.rp9')
,('rpss' , 'Nokia Radio Application - Preset' , 'application/vnd.nokia.radio-presets')
,('rpst' , 'Nokia Radio Application - Preset' , 'application/vnd.nokia.radio-preset')
,('rq' , 'SPARQL - Query' , 'application/sparql-query')
,('rs' , 'XML Resource Lists' , 'application/rls-services+xml')
,('rsd' , 'Really Simple Discovery' , 'application/rsd+xml')
,('rss, .xml' , 'RSS - Really Simple Syndication' , 'application/rss+xml')
,('rtf' , 'Rich Text Format' , 'application/rtf')
,('rtx' , 'Rich Text Format (RTF)' , 'text/richtext')
,('s' , 'Assembler Source File' , 'text/x-asm')
,('saf' , 'SMAF Audio' , 'application/vnd.yamaha.smaf-audio')
,('sbml' , 'Systems Biology Markup Language' , 'application/sbml+xml')
,('sc' , 'IBM Electronic Media Management System - Secure Container' , 'application/vnd.ibm.secure-container')
,('scd' , 'Microsoft Schedule+' , 'application/x-msschedule')
,('scm' , 'Lotus Screencam' , 'application/vnd.lotus-screencam')
,('scq' , 'Server-Based Certificate Validation Protocol - Validation Request' , 'application/scvp-cv-request')
,('scs' , 'Server-Based Certificate Validation Protocol - Validation Response' , 'application/scvp-cv-response')
,('scurl' , 'Curl - Source Code' , 'text/vnd.curl.scurl')
,('sda' , 'StarOffice - Draw' , 'application/vnd.stardivision.draw')
,('sdc' , 'StarOffice - Calc' , 'application/vnd.stardivision.calc')
,('sdd' , 'StarOffice - Impress' , 'application/vnd.stardivision.impress')
,('sdkm' , 'SudokuMagic' , 'application/vnd.solent.sdkm+xml')
,('sdp' , 'Session Description Protocol' , 'application/sdp')
,('sdw' , 'StarOffice - Writer' , 'application/vnd.stardivision.writer')
,('see' , 'SeeMail' , 'application/vnd.seemail')
,('seed' , 'Digital Siesmograph Networks - SEED Datafiles' , 'application/vnd.fdsn.seed')
,('sema' , 'Secured eMail' , 'application/vnd.sema')
,('semd' , 'Secured eMail' , 'application/vnd.semd')
,('semf' , 'Secured eMail' , 'application/vnd.semf')
,('ser' , 'Java Serialized Object' , 'application/java-serialized-object')
,('setpay' , 'Secure Electronic Transaction - Payment' , 'application/set-payment-initiation')
,('setreg' , 'Secure Electronic Transaction - Registration' , 'application/set-registration-initiation')
,('sfd-hdstx' , 'Hydrostatix Master Suite' , 'application/vnd.hydrostatix.sof-data')
,('sfs' , 'TIBCO Spotfire' , 'application/vnd.spotfire.sfs')
,('sgl' , 'StarOffice - Writer (Global)' , 'application/vnd.stardivision.writer-global')
,('sgml' , 'Standard Generalized Markup Language (SGML)' , 'text/sgml')
,('sh' , 'Bourne Shell Script' , 'application/x-sh')
,('shar' , 'Shell Archive' , 'application/x-shar')
,('shf' , 'S Hexdump Format' , 'application/shf+xml')
,('sis' , 'Symbian Install Package' , 'application/vnd.symbian.install')
,('sit' , 'Stuffit Archive' , 'application/x-stuffit')
,('sitx' , 'Stuffit Archive' , 'application/x-stuffitx')
,('skp' , 'SSEYO Koan Play File' , 'application/vnd.koan')
,('sldm' , 'Microsoft PowerPoint - Macro-Enabled Open XML Slide' , 'application/vnd.ms-powerpoint.slide.macroenabled.12')
,('sldx' , 'Microsoft Office - OOXML - Presentation (Slide)' , 'application/vnd.openxmlformats-officedocument.presentationml.slide')
,('slt' , 'SimpleAnimeLite Player' , 'application/vnd.epson.salt')
,('sm' , 'StepMania' , 'application/vnd.stepmania.stepchart')
,('smf' , 'StarOffice - Math' , 'application/vnd.stardivision.math')
,('smi' , 'Synchronized Multimedia Integration Language' , 'application/smil+xml')
,('snf' , 'Server Normal Format' , 'application/x-font-snf')
,('spf' , 'SMAF Phrase' , 'application/vnd.yamaha.smaf-phrase')
,('spl' , 'FutureSplash Animator' , 'application/x-futuresplash')
,('spot' , 'In3D - 3DML' , 'text/vnd.in3d.spot')
,('spp' , 'Server-Based Certificate Validation Protocol - Validation Policies - Response' , 'application/scvp-vp-response')
,('spq' , 'Server-Based Certificate Validation Protocol - Validation Policies - Request' , 'application/scvp-vp-request')
,('src' , 'WAIS Source' , 'application/x-wais-source')
,('sru' , 'Search/Retrieve via URL Response Format' , 'application/sru+xml')
,('srx' , 'SPARQL - Results' , 'application/sparql-results+xml')
,('sse' , 'Kodak Storyshare' , 'application/vnd.kodak-descriptor')
,('ssf' , 'QUASS Stream Player' , 'application/vnd.epson.ssf')
,('ssml' , 'Speech Synthesis Markup Language' , 'application/ssml+xml')
,('st' , 'SailingTracker' , 'application/vnd.sailingtracker.track')
,('stc' , 'OpenOffice - Calc Template (Spreadsheet)' , 'application/vnd.sun.xml.calc.template')
,('std' , 'OpenOffice - Draw Template (Graphics)' , 'application/vnd.sun.xml.draw.template')
,('stf' , 'Worldtalk' , 'application/vnd.wt.stf')
,('sti' , 'OpenOffice - Impress Template (Presentation)' , 'application/vnd.sun.xml.impress.template')
,('stk' , 'Hyperstudio' , 'application/hyperstudio')
,('stl' , 'Microsoft Trust UI Provider - Certificate Trust Link' , 'application/vnd.ms-pki.stl')
,('str' , 'Proprietary P&G Standard Reporting System' , 'application/vnd.pg.format')
,('stw' , 'OpenOffice - Writer Template (Text - HTML)' , 'application/vnd.sun.xml.writer.template')
,('sub' , 'Close Captioning - Subtitle' , 'image/vnd.dvb.subtitle')
,('sus' , 'ScheduleUs' , 'application/vnd.sus-calendar')
,('sv4cpio' , 'System V Release 4 CPIO Archive' , 'application/x-sv4cpio')
,('sv4crc' , 'System V Release 4 CPIO Checksum Data' , 'application/x-sv4crc')
,('svc' , 'Digital Video Broadcasting' , 'application/vnd.dvb.service')
,('svd' , 'SourceView Document' , 'application/vnd.svd')
,('svg' , 'Scalable Vector Graphics (SVG)' , 'image/svg+xml')
,('swf' , 'Adobe Flash' , 'application/x-shockwave-flash')
,('swi' , 'Arista Networks Software Image' , 'application/vnd.aristanetworks.swi')
,('sxc' , 'OpenOffice - Calc (Spreadsheet)' , 'application/vnd.sun.xml.calc')
,('sxd' , 'OpenOffice - Draw (Graphics)' , 'application/vnd.sun.xml.draw')
,('sxg' , 'OpenOffice - Writer (Text - HTML)' , 'application/vnd.sun.xml.writer.global')
,('sxi' , 'OpenOffice - Impress (Presentation)' , 'application/vnd.sun.xml.impress')
,('sxm' , 'OpenOffice - Math (Formula)' , 'application/vnd.sun.xml.math')
,('sxw' , 'OpenOffice - Writer (Text - HTML)' , 'application/vnd.sun.xml.writer')
,('t' , 'troff' , 'text/troff')
,('tao' , 'Tao Intent' , 'application/vnd.tao.intent-module-archive')
,('tar' , 'Tar File (Tape Archive)' , 'application/x-tar')
,('tcap' , '3rd Generation Partnership Project - Transaction Capabilities Application Part' , 'application/vnd.3gpp2.tcap')
,('tcl' , 'Tcl Script' , 'application/x-tcl')
,('teacher' , 'SMART Technologies Apps' , 'application/vnd.smart.teacher')
,('tei' , 'Text Encoding and Interchange' , 'application/tei+xml')
,('tex' , 'TeX' , 'application/x-tex')
,('texinfo' , 'GNU Texinfo Document' , 'application/x-texinfo')
,('tfi' , 'Sharing Transaction Fraud Data' , 'application/thraud+xml')
,('tfm' , 'TeX Font Metric' , 'application/x-tex-tfm')
,('thmx' , 'Microsoft Office System Release Theme' , 'application/vnd.ms-officetheme')
,('tiff' , 'Tagged Image File Format' , 'image/tiff')
,('tmo' , 'MobileTV' , 'application/vnd.tmobile-livetv')
,('torrent' , 'BitTorrent' , 'application/x-bittorrent')
,('tpl' , 'Groove - Tool Template' , 'application/vnd.groove-tool-template')
,('tpt' , 'TRI Systems Config' , 'application/vnd.trid.tpt')
,('tra' , 'True BASIC' , 'application/vnd.trueapp')
,('trm' , 'Microsoft Windows Terminal Services' , 'application/x-msterminal')
,('tsd' , 'Time Stamped Data Envelope' , 'application/timestamped-data')
,('tsv' , 'Tab Seperated Values' , 'text/tab-separated-values')
,('ttf' , 'TrueType Font' , 'application/x-font-ttf')
,('ttl' , 'Turtle (Terse RDF Triple Language)' , 'text/turtle')
,('twd' , 'SimTech MindMapper' , 'application/vnd.simtech-mindmapper')
,('txd' , 'Genomatix Tuxedo Framework' , 'application/vnd.genomatix.tuxedo')
,('txf' , 'Mobius Management Systems - Topic Index File' , 'application/vnd.mobius.txf')
,('txt' , 'Text File' , 'text/plain')
,('ufd' , 'Universal Forms Description Language' , 'application/vnd.ufdl')
,('umj' , 'UMAJIN' , 'application/vnd.umajin')
,('unityweb' , 'Unity 3d' , 'application/vnd.unity')
,('uoml' , 'Unique Object Markup Language' , 'application/vnd.uoml+xml')
,('uri' , 'URI Resolution Services' , 'text/uri-list')
,('ustar' , 'Ustar (Uniform Standard Tape Archive)' , 'application/x-ustar')
,('utz' , 'User Interface Quartz - Theme (Symbian)' , 'application/vnd.uiq.theme')
,('uu' , 'UUEncode' , 'text/x-uuencode')
,('uva' , 'DECE Audio' , 'audio/vnd.dece.audio')
,('uvh' , 'DECE High Definition Video' , 'video/vnd.dece.hd')
,('uvi' , 'DECE Graphic' , 'image/vnd.dece.graphic')
,('uvm' , 'DECE Mobile Video' , 'video/vnd.dece.mobile')
,('uvp' , 'DECE PD Video' , 'video/vnd.dece.pd')
,('uvs' , 'DECE SD Video' , 'video/vnd.dece.sd')
,('uvu' , 'DECE MP4' , 'video/vnd.uvvu.mp4')
,('uvv' , 'DECE Video' , 'video/vnd.dece.video')
,('vcd' , 'Video CD' , 'application/x-cdlink')
,('vcf' , 'vCard' , 'text/x-vcard')
,('vcg' , 'Groove - Vcard' , 'application/vnd.groove-vcard')
,('vcs' , 'vCalendar' , 'text/x-vcalendar')
,('vcx' , 'VirtualCatalog' , 'application/vnd.vcx')
,('vis' , 'Visionary' , 'application/vnd.visionary')
,('viv' , 'Vivo' , 'video/vnd.vivo')
,('vsd' , 'Microsoft Visio' , 'application/vnd.visio')
,('vsdx' , 'Microsoft Visio 2013' , 'application/vnd.visio2013')
,('vsf' , 'Viewport+' , 'application/vnd.vsf')
,('vtu' , 'Virtue VTU' , 'model/vnd.vtu')
,('vxml' , 'VoiceXML' , 'application/voicexml+xml')
,('wad' , 'Doom Video Game' , 'application/x-doom')
,('wav' , 'Waveform Audio File Format (WAV)' , 'audio/x-wav')
,('wax' , 'Microsoft Windows Media Audio Redirector' , 'audio/x-ms-wax')
,('wbmp' , 'WAP Bitamp (WBMP)' , 'image/vnd.wap.wbmp')
,('wbs' , 'Critical Tools - PERT Chart EXPERT' , 'application/vnd.criticaltools.wbs+xml')
,('wbxml' , 'WAP Binary XML (WBXML)' , 'application/vnd.wap.wbxml')
,('weba' , 'Open Web Media Project - Audio' , 'audio/webm')
,('webm' , 'Open Web Media Project - Video' , 'video/webm')
,('webp' , 'WebP Image' , 'image/webp')
,('wg' , 'Qualcomm''s Plaza Mobile Internet' , 'application/vnd.pmi.widget')
,('wgt' , 'Widget Packaging and XML Configuration' , 'application/widget')
,('wm' , 'Microsoft Windows Media' , 'video/x-ms-wm')
,('wma' , 'Microsoft Windows Media Audio' , 'audio/x-ms-wma')
,('wmd' , 'Microsoft Windows Media Player Download Package' , 'application/x-ms-wmd')
,('wmf' , 'Microsoft Windows Metafile' , 'application/x-msmetafile')
,('wml' , 'Wireless Markup Language (WML)' , 'text/vnd.wap.wml')
,('wmlc' , 'Compiled Wireless Markup Language (WMLC)' , 'application/vnd.wap.wmlc')
,('wmls' , 'Wireless Markup Language Script (WMLScript)' , 'text/vnd.wap.wmlscript')
,('wmlsc' , 'WMLScript' , 'application/vnd.wap.wmlscriptc')
,('wmv' , 'Microsoft Windows Media Video' , 'video/x-ms-wmv')
,('wmx' , 'Microsoft Windows Media Audio/Video Playlist' , 'video/x-ms-wmx')
,('wmz' , 'Microsoft Windows Media Player Skin Package' , 'application/x-ms-wmz')
,('woff' , 'Web Open Font Format' , 'application/x-font-woff')
,('wpd' , 'Wordperfect' , 'application/vnd.wordperfect')
,('wpl' , 'Microsoft Windows Media Player Playlist' , 'application/vnd.ms-wpl')
,('wps' , 'Microsoft Works' , 'application/vnd.ms-works')
,('wqd' , 'SundaHus WQ' , 'application/vnd.wqd')
,('wri' , 'Microsoft Wordpad' , 'application/x-mswrite')
,('wrl' , 'Virtual Reality Modeling Language' , 'model/vrml')
,('wsdl' , 'WSDL - Web Services Description Language' , 'application/wsdl+xml')
,('wspolicy' , 'Web Services Policy' , 'application/wspolicy+xml')
,('wtb' , 'WebTurbo' , 'application/vnd.webturbo')
,('wvx' , 'Microsoft Windows Media Video Playlist' , 'video/x-ms-wvx')
,('x3d' , '3D Crossword Plugin' , 'application/vnd.hzn-3d-crossword')
,('xap' , 'Microsoft Silverlight' , 'application/x-silverlight-app')
,('xar' , 'CorelXARA' , 'application/vnd.xara')
,('xbap' , 'Microsoft XAML Browser Application' , 'application/x-ms-xbap')
,('xbd' , 'Fujitsu - Xerox DocuWorks Binder' , 'application/vnd.fujixerox.docuworks.binder')
,('xbm' , 'X BitMap' , 'image/x-xbitmap')
,('xdf' , 'XML Configuration Access Protocol - XCAP Diff' , 'application/xcap-diff+xml')
,('xdm' , 'SyncML - Device Management' , 'application/vnd.syncml.dm+xml')
,('xdp' , 'Adobe XML Data Package' , 'application/vnd.adobe.xdp+xml')
,('xdssc' , 'Data Structure for the Security Suitability of Cryptographic Algorithms' , 'application/dssc+xml')
,('xdw' , 'Fujitsu - Xerox DocuWorks' , 'application/vnd.fujixerox.docuworks')
,('xenc' , 'XML Encryption Syntax and Processing' , 'application/xenc+xml')
,('xer' , 'XML Patch Framework' , 'application/patch-ops-error+xml')
,('xfdf' , 'Adobe XML Forms Data Format' , 'application/vnd.adobe.xfdf')
,('xfdl' , 'Extensible Forms Description Language' , 'application/vnd.xfdl')
,('xhtml' , 'XHTML - The Extensible HyperText Markup Language' , 'application/xhtml+xml')
,('xif' , 'eXtended Image File Format (XIFF)' , 'image/vnd.xiff')
,('xlam' , 'Microsoft Excel - Add-In File' , 'application/vnd.ms-excel.addin.macroenabled.12')
,('xls' , 'Microsoft Excel' , 'application/vnd.ms-excel')
,('xlsb' , 'Microsoft Excel - Binary Workbook' , 'application/vnd.ms-excel.sheet.binary.macroenabled.12')
,('xlsm' , 'Microsoft Excel - Macro-Enabled Workbook' , 'application/vnd.ms-excel.sheet.macroenabled.12')
,('xlsx' , 'Microsoft Office - OOXML - Spreadsheet' , 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
,('xltm' , 'Microsoft Excel - Macro-Enabled Template File' , 'application/vnd.ms-excel.template.macroenabled.12')
,('xltx' , 'Microsoft Office - OOXML - Spreadsheet Template' , 'application/vnd.openxmlformats-officedocument.spreadsheetml.template')
,('xml' , 'XML - Extensible Markup Language' , 'application/xml')
,('xo' , 'Sugar Linux Application Bundle' , 'application/vnd.olpc-sugar')
,('xop' , 'XML-Binary Optimized Packaging' , 'application/xop+xml')
,('xpi' , 'XPInstall - Mozilla' , 'application/x-xpinstall')
,('xpm' , 'X PixMap' , 'image/x-xpixmap')
,('xpr' , 'Express by Infoseek' , 'application/vnd.is-xpr')
,('xps' , 'Microsoft XML Paper Specification' , 'application/vnd.ms-xpsdocument')
,('xpw' , 'Intercon FormNet' , 'application/vnd.intercon.formnet')
,('xslt' , 'XML Transformations' , 'application/xslt+xml')
,('xsm' , 'SyncML' , 'application/vnd.syncml+xml')
,('xspf' , 'XSPF - XML Shareable Playlist Format' , 'application/xspf+xml')
,('xul' , 'XUL - XML User Interface Language' , 'application/vnd.mozilla.xul+xml')
,('xwd' , 'X Window Dump' , 'image/x-xwindowdump')
,('xyz' , 'XYZ File Format' , 'chemical/x-xyz')
,('yaml' , 'YAML Ain''t Markup Language / Yet Another Markup Language' , 'text/yaml')
,('yang' , 'YANG Data Modeling Language' , 'application/yang')
,('yin' , 'YIN (YANG - XML)' , 'application/yin+xml')
,('zaz' , 'Zzazz Deck' , 'application/vnd.zzazz.deck+xml')
,('zip' , 'Zip Archive' , 'application/zip')
,('zir' , 'Z.U.L. Geometry' , 'application/vnd.zul')
,('zmm' , 'ZVUE Media Manager' , 'application/vnd.handheld-entertainment+xml')

GO