// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApp.Localisation.DataAccessLayer;

namespace WebApp.Localisation.DataAccessLayer.Migrations
{
    [DbContext(typeof(LocalisationDbContext))]
    partial class LocalisationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Model")
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApp.Localisation.DataAccessLayer.Models.Localisation", b =>
                {
                    b.Property<Guid>("LocalisationId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Key");

                    b.Property<string>("LanguageIsoAlpha2");

                    b.Property<string>("Value");

                    b.HasKey("LocalisationId");

                    b.ToTable("Localisations");
                });
#pragma warning restore 612, 618
        }
    }
}
